---
- name: Create ansible_directory on remote VM
  hosts: localhost
  become: true
  tasks:
    - name: Ensure ansible_directory exists under /
      file:
        path: /ansible_directory-1
        state: directory
        mode: '0755'

  tasks:
    - name: to create remoteuser in ansible host
      ansible.builtin.user:
        name: ruser
        comment: "remote user"
        shell: /bin/ksh
        create_home: yes
        state: present
